import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Client, WorkoutPlan, DietPlan, mealTypeLabels } from '@shared/schema';
import { goalLabels, fitnessLevelLabels } from '@shared/schema';

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

const MEAL_ORDER: Array<keyof typeof mealTypeLabels> = [
  'breakfast', 'snack_morning', 'lunch', 'snack_afternoon', 'dinner'
];

const MEAL_LABELS: Record<string, string> = {
  breakfast: 'Breakfast',
  snack_morning: 'Morning Snack',
  lunch: 'Lunch',
  snack_afternoon: 'Afternoon Snack',
  dinner: 'Dinner',
};

export function generateWorkoutPDF(client: Client, plan: WorkoutPlan): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header with gradient effect
  doc.setFillColor(249, 115, 22); // Orange-500
  doc.rect(0, 0, pageWidth, 45, 'F');
  
  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('WORKOUT PLAN', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(`${MONTH_NAMES[plan.month - 1]} ${plan.year}`, pageWidth / 2, 32, { align: 'center' });
  
  // Client Info Box
  doc.setFillColor(250, 250, 250);
  doc.roundedRect(15, 55, pageWidth - 30, 35, 3, 3, 'F');
  
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Client: ${client.name}`, 22, 68);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Goal: ${goalLabels[client.goal]}`, 22, 78);
  doc.text(`Level: ${fitnessLevelLabels[client.fitnessLevel]}`, 100, 78);
  doc.text(`Age: ${client.age} | Weight: ${client.weight}kg | Height: ${client.height}cm`, 22, 85);
  
  let yPos = 100;
  
  // Group days into weeks
  const weeks: typeof plan.days[] = [];
  for (let i = 0; i < plan.days.length; i += 7) {
    weeks.push(plan.days.slice(i, i + 7));
  }
  
  weeks.forEach((week, weekIndex) => {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    
    // Week header
    doc.setFillColor(249, 115, 22);
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.roundedRect(15, yPos, pageWidth - 30, 8, 2, 2, 'F');
    doc.text(`Week ${weekIndex + 1}`, 20, yPos + 6);
    yPos += 12;
    
    week.forEach((day) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setTextColor(50, 50, 50);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`Day ${day.day}${day.isRestDay ? ' - REST DAY' : ''}`, 20, yPos);
      yPos += 5;
      
      if (!day.isRestDay && day.exercises.length > 0) {
        const tableData = day.exercises.map(ex => [
          ex.name,
          `${ex.sets} x ${ex.reps}`,
          `${ex.restSeconds}s`,
          ex.notes || '-'
        ]);
        
        autoTable(doc, {
          startY: yPos,
          head: [['Exercise', 'Sets x Reps', 'Rest', 'Notes']],
          body: tableData,
          margin: { left: 20, right: 20 },
          headStyles: { 
            fillColor: [249, 115, 22],
            fontSize: 8,
            fontStyle: 'bold'
          },
          bodyStyles: { 
            fontSize: 8,
            cellPadding: 2
          },
          columnStyles: {
            0: { cellWidth: 60 },
            1: { cellWidth: 30 },
            2: { cellWidth: 20 },
            3: { cellWidth: 50 }
          },
          theme: 'striped'
        });
        
        yPos = (doc as any).lastAutoTable.finalY + 8;
      } else {
        yPos += 5;
      }
    });
    
    yPos += 5;
  });
  
  // Footer on each page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by FitPro Trainer | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  return doc;
}

export function generateDietPDF(client: Client, plan: DietPlan): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(34, 197, 94); // Green-500
  doc.rect(0, 0, pageWidth, 45, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('DIET PLAN', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(`${MONTH_NAMES[plan.month - 1]} ${plan.year}`, pageWidth / 2, 32, { align: 'center' });
  
  // Client Info Box
  doc.setFillColor(250, 250, 250);
  doc.roundedRect(15, 55, pageWidth - 30, 35, 3, 3, 'F');
  
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Client: ${client.name}`, 22, 68);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Daily Target: ${plan.targetCalories} calories`, 22, 78);
  doc.text(`Goal: ${goalLabels[client.goal]}`, 100, 78);
  doc.text(`Age: ${client.age} | Weight: ${client.weight}kg | Height: ${client.height}cm`, 22, 85);
  
  let yPos = 100;
  
  // Group days into weeks
  const weeks: typeof plan.days[] = [];
  for (let i = 0; i < plan.days.length; i += 7) {
    weeks.push(plan.days.slice(i, i + 7));
  }
  
  weeks.forEach((week, weekIndex) => {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    
    // Week header
    doc.setFillColor(34, 197, 94);
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.roundedRect(15, yPos, pageWidth - 30, 8, 2, 2, 'F');
    doc.text(`Week ${weekIndex + 1}`, 20, yPos + 6);
    yPos += 12;
    
    week.forEach((day) => {
      if (yPos > 260) {
        doc.addPage();
        yPos = 20;
      }
      
      const totalCalories = day.meals.reduce((sum, m) => sum + m.calories, 0);
      
      doc.setTextColor(50, 50, 50);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`Day ${day.day} - ${totalCalories} kcal | Water: ${day.waterIntake}L`, 20, yPos);
      yPos += 5;
      
      if (day.meals.length > 0) {
        const sortedMeals = [...day.meals].sort((a, b) => 
          MEAL_ORDER.indexOf(a.type as any) - MEAL_ORDER.indexOf(b.type as any)
        );
        
        const tableData = sortedMeals.map(meal => [
          MEAL_LABELS[meal.type],
          meal.name,
          `${meal.calories}`,
          `${meal.protein}g`,
          `${meal.carbs}g`,
          `${meal.fat}g`
        ]);
        
        autoTable(doc, {
          startY: yPos,
          head: [['Meal', 'Food', 'Cal', 'Protein', 'Carbs', 'Fat']],
          body: tableData,
          margin: { left: 20, right: 20 },
          headStyles: { 
            fillColor: [34, 197, 94],
            fontSize: 7,
            fontStyle: 'bold'
          },
          bodyStyles: { 
            fontSize: 7,
            cellPadding: 2
          },
          columnStyles: {
            0: { cellWidth: 30 },
            1: { cellWidth: 55 },
            2: { cellWidth: 20 },
            3: { cellWidth: 20 },
            4: { cellWidth: 20 },
            5: { cellWidth: 20 }
          },
          theme: 'striped'
        });
        
        yPos = (doc as any).lastAutoTable.finalY + 6;
      } else {
        yPos += 5;
      }
    });
    
    yPos += 5;
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by FitPro Trainer | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  return doc;
}

export function generateCombinedPDF(
  client: Client, 
  workoutPlan: WorkoutPlan | null, 
  dietPlan: DietPlan | null
): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Cover Page
  doc.setFillColor(249, 115, 22);
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.text('FITPRO', pageWidth / 2, 80, { align: 'center' });
  
  doc.setFontSize(18);
  doc.text('COMPLETE FITNESS PLAN', pageWidth / 2, 100, { align: 'center' });
  
  doc.setFontSize(24);
  doc.text(client.name, pageWidth / 2, 140, { align: 'center' });
  
  const month = workoutPlan?.month || dietPlan?.month || new Date().getMonth() + 1;
  const year = workoutPlan?.year || dietPlan?.year || new Date().getFullYear();
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.text(`${MONTH_NAMES[month - 1]} ${year}`, pageWidth / 2, 160, { align: 'center' });
  
  // Client stats
  doc.setFontSize(12);
  doc.text(`Goal: ${goalLabels[client.goal]}`, pageWidth / 2, 200, { align: 'center' });
  doc.text(`Fitness Level: ${fitnessLevelLabels[client.fitnessLevel]}`, pageWidth / 2, 215, { align: 'center' });
  doc.text(`Age: ${client.age} | Weight: ${client.weight}kg | Height: ${client.height}cm`, pageWidth / 2, 230, { align: 'center' });
  
  // Add workout plan pages if exists
  if (workoutPlan) {
    const workoutDoc = generateWorkoutPDF(client, workoutPlan);
    const workoutPages = workoutDoc.getNumberOfPages();
    
    for (let i = 1; i <= workoutPages; i++) {
      doc.addPage();
      // Copy content would require more complex implementation
      // For now, we'll add a reference page
      if (i === 1) {
        doc.setFillColor(249, 115, 22);
        doc.rect(0, 0, pageWidth, 30, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(20);
        doc.setFont('helvetica', 'bold');
        doc.text('WORKOUT PLAN', pageWidth / 2, 20, { align: 'center' });
      }
    }
  }
  
  // Add diet plan pages if exists
  if (dietPlan) {
    const dietDoc = generateDietPDF(client, dietPlan);
    const dietPages = dietDoc.getNumberOfPages();
    
    for (let i = 1; i <= dietPages; i++) {
      doc.addPage();
      if (i === 1) {
        doc.setFillColor(34, 197, 94);
        doc.rect(0, 0, pageWidth, 30, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(20);
        doc.setFont('helvetica', 'bold');
        doc.text('DIET PLAN', pageWidth / 2, 20, { align: 'center' });
      }
    }
  }
  
  return doc;
}

export function downloadPDF(doc: jsPDF, filename: string) {
  doc.save(filename);
}

export function getPDFBlob(doc: jsPDF): Blob {
  return doc.output('blob');
}

export function shareToWhatsApp(message: string, phone?: string) {
  const encodedMessage = encodeURIComponent(message);
  const baseUrl = phone 
    ? `https://wa.me/${phone.replace(/\D/g, '')}?text=${encodedMessage}`
    : `https://wa.me/?text=${encodedMessage}`;
  window.open(baseUrl, '_blank');
}
